server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbGirls?useSSL=false
    username: fourier
    password: MotoV3~~
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update